
export interface Project {
  id: string;
  title: string;
  description: string;
  icon?: string;
  image: string;
  video?: string;
  images?: string[];
  videos?: { title: string; url: string }[];
  tags: string[];
  link: string;
  github: string;
  category: 'mobile' | 'web' | 'macos' | 'design' | 'videography';
  platform?: string; // e.g. "Play Store", "App Store", "macOS"
  featured: boolean;
  color: string;
}

export const projects: Project[] = [
  // ── MOBILE APPS ─────────────────────────────────────────────────────────────
  {
    id: "nimbus-ai",
    title: "NimbusAi",
    description: "On-device AI chatbot powered by Gemma 4 — text chat, image Q&A, and voice-to-text with zero cloud.",
    icon: "/icons/nimbus-ai.png",
    image: "/icons/nimbus-ai.png",
    tags: ["Flutter", "Gemma 4", "Riverpod", "Cloudflare R2"],
    link: "#",
    github: "#",
    platform: "Play Store",
    category: "mobile",
    featured: true,
    color: "from-violet-500 to-purple-600",
  },
  {
    id: "edux",
    title: "EDU_X",
    description: "Offline school hub with desktop and teacher apps, auto-synced over local WiFi using mDNS.",
    icon: "/icons/edux.png",
    image: "/icons/poul3y.png",
    tags: ["Flutter", "SQLite/Drift", "mDNS WiFi Sync"],
    link: "#",
    github: "#",
    platform: "Play Store",
    category: "mobile",
    featured: true,
    color: "from-sky-500 to-indigo-600",
  },
  {
    id: "freezer",
    title: "Freezer",
    description: "Blocks app network access via a local VPN and suppresses notifications — fully Play Store compliant.",
    icon: "/icons/freezer.png",
    image: "/icons/freezer.png",
    tags: ["Flutter", "Kotlin", "Android VpnService", "Hive"],
    link: "#",
    github: "#",
    platform: "Play Store",
    category: "mobile",
    featured: true,
    color: "from-cyan-500 to-slate-600",
  },
  {
    id: "scriptflow",
    title: "ScriptFlow",
    description: "Floating teleprompter for content creators — overlays any app and auto-scrolls scripts with optional speech following.",
    icon: "/icons/scriptflow.png",
    image: "/icons/scriptflow.png",
    tags: ["Flutter", "Kotlin", "Android WindowManager", "Speech Recognition"],
    link: "#",
    github: "#",
    platform: "Play Store",
    category: "mobile",
    featured: false,
    color: "from-purple-500 to-blue-600",
  },
  {
    id: "boot-alarm",
    title: "Boot Alarm",
    description: "Developer alarm: solve a programming MCQ to dismiss. Covers Python, C++, JS, ML, and Networking with a neumorphic UI.",
    icon: "/icons/boot-alarm.png",
    image: "/icons/boot-alarm.png",
    tags: ["Flutter", "sqflite", "Provider", "Neumorphic UI"],
    link: "#",
    github: "#",
    platform: "Play Store",
    category: "mobile",
    featured: false,
    color: "from-indigo-500 to-fuchsia-600",
  },
  {
    id: "pneumoscan",
    title: "PneumoScan",
    description: "AI chest X-ray analyser for pneumonia detection with built-in guidance on symptoms, causes, and treatment.",
    icon: "/icons/pneumoscan.png",
    image: "/icons/pneumoscan.png",
    tags: ["Android", "Java", "CameraX", "AI Inference"],
    link: "#",
    github: "#",
    platform: "Play Store",
    category: "mobile",
    featured: false,
    color: "from-blue-500 to-teal-600",
  },
  {
    id: "poultry-calculator",
    title: "Poultry Calculator",
    description: "Feed calculator for poultry farmers — pick bird type and flock size to generate an instant shareable receipt.",
    icon: "/icons/poultry-calculator.png",
    image: "/icons/poultry-calculator.png",
    platform: "Play Store",
    tags: ["Flutter", "Dart"],
    link: "#",
    github: "#",
    category: "mobile",
    featured: false,
    color: "from-orange-500 to-amber-600",
  },
  {
    id: "offline-cv",
    title: "Offline CV Builder",
    description: "Privacy-first offline resume builder with multiple templates and PDF export — no accounts or servers required.",
    icon: "/icons/offline-cv.png",
    image: "/icons/offline-cv.png",
    platform: "Play Store",
    tags: ["Flutter", "Dart", "PDF Export"],
    link: "#",
    github: "#",
    category: "mobile",
    featured: false,
    color: "from-stone-500 to-sky-600",
  },
  {
    id: "promptly",
    title: "Promptly",
    description: "AI prompt gallery with 300+ curated prompts for image generation, category browsing, and a favourites system.",
    icon: "/icons/promptly.png",
    image: "/icons/promptly.png",
    tags: ["Flutter", "Firebase", "Riverpod"],
    link: "#",
    github: "#",
    platform: "Play Store",
    category: "mobile",
    featured: false,
    color: "from-rose-500 to-violet-600",
  },
  {
    id: "dice-and-dares",
    title: "Dice & Dares",
    description: "Dice and dare party game with multiple themed modes, difficulty levels, and Google Play Games achievements.",
    icon: "/icons/dice-and-dare.png",
    image: "/icons/dice-and-dare.png",
    tags: ["Flutter", "Google Play Games", "Provider"],
    link: "#",
    github: "#",
    platform: "Play Store",
    category: "mobile",
    featured: false,
    color: "from-pink-500 to-orange-600",
  },
  {
    id: "poul3y",
    title: "Poul3y",
    description: "Digital poultry platform with flock records, disease tracking, resource planning, and PDF reports.",
    icon: "/icons/poul3y.png",
    image: "/icons/poul3y.png",
    tags: ["Flutter", "Firebase", "Figma", "UI/UX"],
    link: "https://www.figma.com/proto/DlvNVRULKgxqMXLcuGbKaT/Poul3y?t=atrFCjSIZ2aDvBzX-1",
    github: "#",
    platform: "Play Store",
    category: "mobile",
    featured: true,
    color: "from-orange-500 to-red-600",
  },
  {
    id: "flock-manager",
    title: "Flock Manager",
    description: "Full-cycle poultry app covering flock setup, mortality, feed, vaccines, warehouse, and team reporting.",
    icon: "/icons/flock-manager.png",
    image: "/icons/flock-manager.png",
    tags: ["Flutter", "Firebase", "Reports"],
    link: "#",
    github: "#",
    platform: "Play Store",
    category: "mobile",
    featured: false,
    color: "from-orange-500 to-amber-600",
  },
  {
    id: "sensor-fusion",
    title: "Sensor Fusion",
    description: "Android app streaming accelerometer, gyroscope, GPS, and barometer data to MQTT or HTTP at up to 400 Hz.",
    icon: "/icons/sensor-fusion.png",
    image: "/icons/sensor-fusion.png",
    tags: ["Android", "Java", "MQTT", "HTTP"],
    link: "#",
    github: "#",
    platform: "Play Store",
    category: "mobile",
    featured: false,
    color: "from-teal-500 to-blue-600",
  },
  {
    id: "jarvis",
    title: "Jarvis",
    description: "Flutter voice AI assistant — text or speech commands routed through a Python Flask and OpenAI backend.",
    icon: undefined,
    image: "/icons/nimbus-ai.png",
    platform: "Play Store",
    tags: ["Flutter", "Python Flask", "OpenAI", "Speech-to-Text"],
    link: "#",
    github: "https://github.com/asimsafeer/Jarvis",
    category: "mobile",
    featured: false,
    color: "from-cyan-500 to-blue-600",
  },
  // ── WEB APPS ─────────────────────────────────────────────────────────────────
  {
    id: "portfolio-website",
    title: "Portfolio Website",
    description: "Developer portfolio built with Next.js and Tailwind CSS, showcasing projects, skills, and career.",
    icon: undefined,
    image: "/icons/poul3y.png",
    platform: "Live",
    tags: ["Next.js", "TypeScript", "Tailwind CSS"],
    link: "https://aasimsafeer.vercel.app",
    github: "#",
    category: "web",
    featured: false,
    color: "from-blue-500 to-cyan-600",
  },
  {
    id: "expense-tracker",
    title: "Expense Tracker",
    description: "Expense tracker with category-based reports, plus a client-side offline PDF resume generator.",
    icon: "/icons/expense-tracker.png",
    image: "/icons/expense-tracker.png",
    platform: "Live",
    tags: ["Next.js", "TypeScript", "Tailwind CSS"],
    link: "#",
    github: "#",
    category: "web",
    featured: false,
    color: "from-emerald-500 to-green-600",
  },
  {
    id: "virtual-assistant",
    title: "Virtual Assistant",
    description: "Python voice assistant with speech recognition and OpenAI queries — web browsing, music, and a Flask web UI.",
    icon: undefined,
    image: "/icons/expense-tracker.png",
    tags: ["Python", "Flask", "OpenAI", "Speech Recognition"],
    link: "#",
    github: "https://github.com/asimsafeer/Virtual-Assistant",
    category: "web",
    featured: false,
    color: "from-amber-500 to-orange-600",
  },
  // ── macOS ────────────────────────────────────────────────────────────────────
  {
    id: "notchhub",
    title: "NotchHub",
    description: "Turns the MacBook notch into a productivity hub: media controls, file shelf, AI tools, and live system stats.",
    icon: "/icons/notchhub.png",
    image: "/icons/nimbus-ai.png",
    platform: "macOS .dmg",
    tags: ["Swift", "SwiftUI", "AppKit", "AVFoundation"],
    link: "#",
    github: "#",
    category: "macos",
    featured: true,
    color: "from-gray-600 to-slate-700",
  },
  // ── GRAPHIC DESIGN ───────────────────────────────────────────────────────────
  {
    id: "cems-design",
    title: "CEMS Brand Identity",
    description: "Full visual identity for CEMS — hiring posts, branded templates, and a consistent design language.",
    icon: undefined,
    image: "/assets/portfolio/AasimSafeer-Portfolio/CEMS Job Ads/Creative Engineering and Management Services Logo.png",
    images: [
      "/assets/portfolio/AasimSafeer-Portfolio/CEMS Job Ads/Hiring Posts/1.png",
      "/assets/portfolio/AasimSafeer-Portfolio/CEMS Job Ads/Hiring Posts/2.png",
      "/assets/portfolio/AasimSafeer-Portfolio/CEMS Job Ads/Hiring Posts/3.png",
      "/assets/portfolio/AasimSafeer-Portfolio/CEMS Job Ads/Hiring Posts/4.png",
    ],
    tags: ["Branding", "Social Media", "Canva"],
    link: "#",
    github: "#",
    category: "design",
    featured: true,
    color: "from-purple-500 to-pink-600",
  },
  {
    id: "ecosun-design",
    title: "EcoSun Global Branding",
    description: "Corporate branding for EcoSun Global — brochures, business cards, and social media assets.",
    icon: undefined,
    image: "/assets/portfolio/AasimSafeer-Portfolio/EcoSun Global/Ecosun Global Logo.png",
    tags: ["Print Design", "Corporate Identity", "Canva"],
    link: "https://www.canva.com/design/DAGrWsjV3RY/_j6u0BRSt0Mi92Yu6Og2nA/edit",
    github: "#",
    category: "design",
    featured: false,
    color: "from-green-500 to-emerald-600",
  },
  // ── VIDEOGRAPHY ──────────────────────────────────────────────────────────────
  {
    id: "florid-hotel",
    title: "Florid Hotel Cinematic",
    description: "Cinematic promotional videos showcasing Florid Hotel's luxury and ambiance through dynamic visual storytelling.",
    icon: undefined,
    image: "/assets/portfolio/AasimSafeer-Portfolio/Florid Hotel/Florid Hotel Logo.png",
    video: "/assets/portfolio/AasimSafeer-Portfolio/Florid Hotel/lv_0_20241022195504.mp4",
    tags: ["Cinematography", "Video Editing", "Color Grading"],
    link: "#",
    github: "#",
    category: "videography",
    featured: true,
    color: "from-amber-500 to-yellow-600",
  },
  {
    id: "ecosun-video",
    title: "EcoSun Site Walkthrough",
    description: "On-site promotional video documenting EcoSun Global's solar installations and company capabilities.",
    icon: undefined,
    image: "/assets/portfolio/AasimSafeer-Portfolio/EcoSun Global/Ecosun Global Logo.png",
    video: "/assets/portfolio/AasimSafeer-Portfolio/EcoSun Global/Site Videos/Peshawar Hotel.MP4",
    tags: ["Corporate Video", "Site Visit", "Documentation"],
    link: "#",
    github: "#",
    category: "videography",
    featured: false,
    color: "from-sky-500 to-blue-600",
  },
];
