
export interface Project {
  id: string;
  title: string;
  description: string;
  icon?: string;
  image: string;
  video?: string;
  images?: string[];
  videos?: { title: string; url: string }[];
  tags: string[];
  link: string;
  github: string;
  category: 'mobile' | 'web' | 'macos' | 'design' | 'videography';
  platform?: string; // e.g. "Play Store", "App Store", "macOS"
  featured: boolean;
  color: string;
}

export const projects: Project[] = [
  // ── MOBILE APPS ─────────────────────────────────────────────────────────────
  {
    id: "nimbus-ai",
    title: "NimbusAi",
    description: "Offline-first AI chatbot running Google Gemma 4 (1.5 GB) 100% on-device — zero cloud inference. Supports text chat, multimodal image Q&A, and voice-to-text, all fully offline.",
    icon: "/icons/nimbus-ai.png",
    image: "/icons/nimbus-ai.png",
    tags: ["Flutter", "Gemma 4", "Riverpod", "Cloudflare R2"],
    link: "#",
    github: "#",
    category: "mobile",
    featured: true,
    color: "from-violet-500 to-purple-600",
  },
  {
    id: "edux",
    title: "EDU_X",
    description: "Offline-first school management system: desktop hub + teacher Android app. Auto-discovers the hub on local WiFi via mDNS for end-of-day attendance sync. Covers fees, licensing, and multi-device sync.",
    icon: undefined,
    image: "/icons/poul3y.png",
    tags: ["Flutter", "SQLite/Drift", "mDNS WiFi Sync"],
    link: "#",
    github: "#",
    category: "mobile",
    featured: true,
    color: "from-sky-500 to-indigo-600",
  },
  {
    id: "freezer",
    title: "Freezer",
    description: "Android app that freezes selected apps by blocking network access via a local VPN (no traffic leaves device) and suppressing notifications — fully Play Store compliant.",
    icon: "/icons/freezer.png",
    image: "/icons/freezer.png",
    tags: ["Flutter", "Kotlin", "Android VpnService", "Hive"],
    link: "#",
    github: "#",
    category: "mobile",
    featured: true,
    color: "from-cyan-500 to-slate-600",
  },
  {
    id: "scriptflow",
    title: "ScriptFlow",
    description: "Floating teleprompter overlay for content creators that renders on top of any app using SYSTEM_ALERT_WINDOW. Auto-scrolls scripts with optional real-time speech following.",
    icon: "/icons/scriptflow.png",
    image: "/icons/scriptflow.png",
    tags: ["Flutter", "Kotlin", "Android WindowManager", "Speech Recognition"],
    link: "#",
    github: "#",
    category: "mobile",
    featured: false,
    color: "from-purple-500 to-blue-600",
  },
  {
    id: "boot-alarm",
    title: "Boot Alarm",
    description: "Smart alarm app for developers: must correctly answer programming MCQs (1,000+ questions across C++, Python, JS, ML/DL, Networking) to dismiss the alarm. Neumorphic UI.",
    icon: "/icons/boot-alarm.png",
    image: "/icons/boot-alarm.png",
    tags: ["Flutter", "sqflite", "Provider", "Neumorphic UI"],
    link: "#",
    github: "#",
    category: "mobile",
    featured: false,
    color: "from-indigo-500 to-fuchsia-600",
  },
  {
    id: "pneumoscan",
    title: "PneumoScan",
    description: "Medical Android app: capture or upload a chest X-ray and receive AI-powered pneumonia analysis. Includes educational modules on symptoms, causes, treatment, and prevention.",
    icon: "/icons/pneumoscan.png",
    image: "/icons/pneumoscan.png",
    tags: ["Android", "Java", "CameraX", "AI Inference"],
    link: "#",
    github: "#",
    category: "mobile",
    featured: false,
    color: "from-blue-500 to-teal-600",
  },
  {
    id: "poultry-calculator",
    title: "Poultry Calculator",
    description: "Feed estimation app for poultry farmers: select bird type (broiler/layer), enter flock size, and instantly generate a shareable feed requirement receipt.",
    icon: "/icons/poultry-calculator.png",
    image: "/icons/poultry-calculator.png",
    platform: "Play Store",
    tags: ["Flutter", "Dart"],
    link: "#",
    github: "#",
    category: "mobile",
    featured: false,
    color: "from-orange-500 to-amber-600",
  },
  {
    id: "offline-cv",
    title: "Offline CV Builder",
    description: "Privacy-first offline resume builder: all data stays on device — no accounts, no servers, no third-party sharing. Multiple templates, PDF export, works 100% without internet.",
    icon: "/icons/offline-cv.png",
    image: "/icons/offline-cv.png",
    platform: "Play Store",
    tags: ["Flutter", "Dart", "PDF Export"],
    link: "#",
    github: "#",
    category: "mobile",
    featured: false,
    color: "from-stone-500 to-sky-600",
  },
  {
    id: "promptly",
    title: "Promptly",
    description: "Premium AI prompt gallery with 300+ curated prompts for image generation. Firebase backend, categorised browsing, and favourites system.",
    icon: "/icons/promptly.png",
    image: "/icons/promptly.png",
    tags: ["Flutter", "Firebase", "Riverpod"],
    link: "#",
    github: "#",
    category: "mobile",
    featured: false,
    color: "from-rose-500 to-violet-600",
  },
  {
    id: "dice-and-dares",
    title: "Dice & Dares",
    description: "Party game combining dice rolls with dare challenges. Multiple themed modes, difficulty levels, and integrated Google Play Games achievements and leaderboards.",
    icon: "/icons/dice-and-dare.png",
    image: "/icons/dice-and-dare.png",
    tags: ["Flutter", "Google Play Games", "Provider"],
    link: "#",
    github: "#",
    category: "mobile",
    featured: false,
    color: "from-pink-500 to-orange-600",
  },
  {
    id: "poul3y",
    title: "Poul3y",
    description: "Digital poultry management platform: real-time flock records, disease tracking, resource planning, PDF reports, and farmer-focused dashboards. Final Year Project.",
    icon: "/icons/poul3y.png",
    image: "/icons/poul3y.png",
    tags: ["Flutter", "Firebase", "Figma", "UI/UX"],
    link: "https://www.figma.com/proto/DlvNVRULKgxqMXLcuGbKaT/Poul3y?t=atrFCjSIZ2aDvBzX-1",
    github: "#",
    category: "mobile",
    featured: true,
    color: "from-orange-500 to-red-600",
  },
  {
    id: "flock-manager",
    title: "Flock Manager",
    description: "Poultry flock operations system covering flock setup, mortality, feed, vaccines, medicine, warehouse, catching, recoveries, reporting, and shared access workflows.",
    icon: "/icons/flock-manager.png",
    image: "/icons/flock-manager.png",
    tags: ["Flutter", "Firebase", "Reports"],
    link: "#",
    github: "#",
    category: "mobile",
    featured: false,
    color: "from-orange-500 to-amber-600",
  },
  {
    id: "sensor-fusion",
    title: "Sensor Fusion",
    description: "Research-grade Android app streaming multi-sensor data (accelerometer, gyroscope, GPS, barometer) to local servers or MQTT brokers. Per-sensor rate control up to 400 Hz.",
    icon: "/icons/sensor-fusion.png",
    image: "/icons/sensor-fusion.png",
    tags: ["Android", "Java", "MQTT", "HTTP"],
    link: "#",
    github: "#",
    category: "mobile",
    featured: false,
    color: "from-teal-500 to-blue-600",
  },
  // ── WEB APPS ─────────────────────────────────────────────────────────────────
  {
    id: "portfolio-website",
    title: "Portfolio Website",
    description: "Personal developer portfolio showcasing projects, skills, and experience. Built with Next.js, TypeScript, and Tailwind CSS with a responsive modern UI.",
    icon: undefined,
    image: "/icons/poul3y.png",
    tags: ["Next.js", "TypeScript", "Tailwind CSS"],
    link: "https://aasimsafeer.vercel.app",
    github: "#",
    category: "web",
    featured: false,
    color: "from-blue-500 to-cyan-600",
  },
  {
    id: "expense-tracker",
    title: "Expense Tracker",
    description: "Personal finance web app with category-based tracking and visual reports. Offline Resume Generator included — client-side resume builder that generates PDFs without a server.",
    icon: "/icons/expense-tracker.png",
    image: "/icons/expense-tracker.png",
    tags: ["Next.js", "TypeScript", "Tailwind CSS"],
    link: "#",
    github: "#",
    category: "web",
    featured: false,
    color: "from-emerald-500 to-green-600",
  },
  // ── macOS ────────────────────────────────────────────────────────────────────
  {
    id: "notchhub",
    title: "NotchHub",
    description: "macOS utility that transforms the MacBook notch into a productivity hub: media controls, file shelf, AI tools, and system stats. Competes with NotchNook, Alcove, and BoringNotch.",
    icon: undefined,
    image: "/icons/nimbus-ai.png",
    platform: "macOS .dmg",
    tags: ["Swift", "SwiftUI", "AppKit", "AVFoundation"],
    link: "#",
    github: "#",
    category: "macos",
    featured: true,
    color: "from-gray-600 to-slate-700",
  },
  // ── GRAPHIC DESIGN ───────────────────────────────────────────────────────────
  {
    id: "cems-design",
    title: "CEMS Brand Identity",
    description: "Complete visual identity and social media campaign for Creative Engineering & Management Services — hiring posts, branded templates, and consistent design language.",
    icon: undefined,
    image: "/assets/portfolio/AasimSafeer-Portfolio/CEMS Job Ads/Creative Engineering and Management Services Logo.png",
    images: [
      "/assets/portfolio/AasimSafeer-Portfolio/CEMS Job Ads/Hiring Posts/1.png",
      "/assets/portfolio/AasimSafeer-Portfolio/CEMS Job Ads/Hiring Posts/2.png",
      "/assets/portfolio/AasimSafeer-Portfolio/CEMS Job Ads/Hiring Posts/3.png",
      "/assets/portfolio/AasimSafeer-Portfolio/CEMS Job Ads/Hiring Posts/4.png",
    ],
    tags: ["Branding", "Social Media", "Canva"],
    link: "#",
    github: "#",
    category: "design",
    featured: true,
    color: "from-purple-500 to-pink-600",
  },
  {
    id: "ecosun-design",
    title: "EcoSun Global Branding",
    description: "Corporate branding package including brochures, business cards, and social media assets for a renewable energy company.",
    icon: undefined,
    image: "/assets/portfolio/AasimSafeer-Portfolio/EcoSun Global/Ecosun Global Logo.png",
    tags: ["Print Design", "Corporate Identity", "Canva"],
    link: "https://www.canva.com/design/DAGrWsjV3RY/_j6u0BRSt0Mi92Yu6Og2nA/edit",
    github: "#",
    category: "design",
    featured: false,
    color: "from-green-500 to-emerald-600",
  },
  // ── VIDEOGRAPHY ──────────────────────────────────────────────────────────────
  {
    id: "florid-hotel",
    title: "Florid Hotel Cinematic",
    description: "Series of cinematic promotional videos showcasing the luxury and ambiance of Florid Hotel — capturing the essence of hospitality through dynamic visual storytelling.",
    icon: undefined,
    image: "/assets/portfolio/AasimSafeer-Portfolio/Florid Hotel/Florid Hotel Logo.png",
    video: "/assets/portfolio/AasimSafeer-Portfolio/Florid Hotel/lv_0_20241022195504.mp4",
    tags: ["Cinematography", "Video Editing", "Color Grading"],
    link: "#",
    github: "#",
    category: "videography",
    featured: true,
    color: "from-amber-500 to-yellow-600",
  },
  {
    id: "ecosun-video",
    title: "EcoSun Site Walkthrough",
    description: "On-site promotional video documenting solar installation projects and company capabilities for EcoSun Global.",
    icon: undefined,
    image: "/assets/portfolio/AasimSafeer-Portfolio/EcoSun Global/Ecosun Global Logo.png",
    video: "/assets/portfolio/AasimSafeer-Portfolio/EcoSun Global/Site Videos/Peshawar Hotel.MP4",
    tags: ["Corporate Video", "Site Visit", "Documentation"],
    link: "#",
    github: "#",
    category: "videography",
    featured: false,
    color: "from-sky-500 to-blue-600",
  },
];
